### ISSUE TITLE
Could you please provide me with this pre-trained model?

### ISSUE THREAD

**Issue by Killerain** [smiles724/ProtMD#2]
Hello! Thank you for your outstanding work. When I tried to run the code "python main.py --data=lba --split=30 --linear_probe --pretrain=model.pt --gpu=0,1,2,3", I was prompted with a missing "model.pt" file. Could you please provide me with this pre-trained model? I think it would be a very enlightening guide to my current work. I would feel honoured to hear from you.

**Comment by smiles724** [comment]
Hi, I have provided the 'model.pt' so you can try it yourself.

Thanks for your interest in our research.

**Comment by Killerain** [comment]
Thanks a lot!
